name: task_manager
description: "A Flutter app to manage tasks with local storage, preferences, and API integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # SQLite support
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.3.0

  path_provider: ^2.1.3
  path: ^1.9.0

  # State persistence
  shared_preferences: ^2.2.2

  # HTTP requests
  http: ^1.2.1

  # For formatting dates
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
